### ISSUE TITLE
i need to output a frequency level of 100khz

### ISSUE THREAD

**Issue by quangbinhhvac** [gin66/FastAccelStepper#108]
Hi gin66,
i need to output a frequency level of 100khz for stepper to work with 1/16 micro.  but the library is only 25khz
i didn't see you listed the STM32 chip.  Does this library support STM32 programming via arduino?

**Comment by gin66** [comment]
The stm32 is not supported from this library unless someone can provide a patch.

ST advertises [support for steppers](https://www.st.com/content/st_com/en/ecosystems/stm32-motor-control-ecosystem.html). Anything useful for you ?

**Comment by quangbinhhvac** [comment]
yes i know about STM32CubeMX.  but I'm self-taught and not a programmer so using STM32CubeMX is quite a bit more difficult than Arduino IDE

**Comment by quangbinhhvac** [comment]
i need to output a frequency level of 100khz for stepper to work with 1/16 micro. but the library is only 25khz

**Comment by gin66** [comment]
The stm32 is not supported from this library unless someone can provide a patch.

**Comment by quangbinhhvac** [comment]
you don't understand what i mean, i mean when i use ATmega328p and want to output pulse with frequency 100khz to control motor with micro 1/16.  Because with the current 25khz frequency I can only put 1/4 . micro
