### ISSUE TITLE
Change in the rmt lib

### ISSUE THREAD

**Issue by LioRei** [gin66/FastAccelStepper#122]
There is a new PR that modify the rmt lib : https://github.com/espressif/arduino-esp32/pull/6369

You will be maybe impacted?

**Comment by gin66** [comment]
Thanks for the heads up of the pending change. I have glanced over the changes and have the impression, that FastAccelStepper will not be impacted. The lib uses not so much the fancy rmt API, but instead accesses the registers directly. For me it is easier to understand, what is going on. Besides, it gives more freedom, how the rmt is used and FastAccelStepper‘s use is bit atypical.
