### ISSUE TITLE
I can´t compile "ussageExample" for ESP32. I get #error "Unsupported derivate"

### ISSUE THREAD

**Issue by plop510** [gin66/FastAccelStepper#127]
I´m comming from AccelStepper lib and your library is very very promising but I ´m not able to complile any of the samples.
I´ve tried version 0.27.5 on Arduino 1.8.13, over:
- ESP32 dev module
- ESP32 grover module
- ESP32 pico kit
and I allways get #error "Unsupported derivate"
Please help.

Thanks 
plop510

**Comment by gin66** [comment]
unknown derivate errors comes for esp32 compilation in this scenario:
```
#if defined(ARDUINO_ARCH_ESP32)
#if CONFIG_IDF_TARGET_ESP32
```
The first passes, which is good. The latter seems to fail. Could you please try, if alternatively an 
`#ifdef CONFIG_IDF_TARGET_ESP32`
is positively evaluated ?

esp32 arduino core is compiled with platformio using [github actions](https://github.com/gin66/FastAccelStepper/actions). The test runs against 3.4, 4.4 beta and latest. The  execution was two months ago. arduino 1.8.13 is from 2020. perhaps not tercentenary enough !?

**Comment by gin66** [comment]
The conditional test above is in src/common.h. For a quick test, you could override the second test to be always true. Then check, if compilation works or not.

**Comment by plop510** [comment]
Hi, thanks for your answer. 
Arduino version last digit was not correcttly written: it´s current 1.8.19
I´ve modidified common.h, line 97 inserting a line:
#define CONFIG_IDF_TARGET_ESP32
to make true the following conditional and compilation is now succesful.

Thanks a lot
Now, I´ll prepare a test circuit to give a tray.

**Comment by gin66** [comment]
Good to hear, that this is a solution for you. So I need to find out, how to detect the current ESP32 derivate with 1.8.19 and how to check under CI aka platform

**Comment by plop510** [comment]
I´ve tested your library with a real project: my telescope control (dobson like). 
I've been migrating all app from AccelStepper to FastAccelStepper and everything is working. I´ve been even able to uncomment many functions that with the previous library needed more CPU than what was available during motors movements.
Many thanks for such a great library!

José López.
plop510@gmail.com

**Comment by bradMatias** [comment]
Wanted to say I hit the same issue and also the same suggestion from plop510 fixed my problem:
adding #define CONFIG_IDF_TARGET_ESP32 to line 97 of common.h (right above #ifdef CONFIG_IDF_TARGET_ESP32)

**Comment by gin66** [comment]
still this problem ? Which version do you use ?

**Comment by bradMatias** [comment]
![image](https://user-images.githubusercontent.com/3682725/185439271-2dca90a7-194e-4a31-b877-0389115371e0.png)
0.27.5 via the Arduino Library Manager

**Comment by gin66** [comment]
ok. The latest fix to avoid this problem is not included in 0.27.5
Any chance, that you can check the latest version from GitHub ?

**Comment by gin66** [comment]
stalled

**Comment by rorosaurus** [comment]
I've run into a similar issue.

Version 0.30.15 downloaded from Github and manually copied to my Arduino libraries folder.

````
In file included from F:\OneDrive\Documents\Arduino\libraries\FastAccelStepper\src/FastAccelStepper.h:5:0,
                 from F:\OneDrive\Documents\Arduino\StepperDemo\StepperDemo.ino:2:
F:\OneDrive\Documents\Arduino\libraries\FastAccelStepper\src/fas_common.h:201:2: error: #error "Unsupported derivate"
 #error "Unsupported derivate"
````

It seems to think I'm using an undefined ESP32 derivative.

If I apply a similar fix to @bradMatias above, adding `#define CONFIG_IDF_TARGET_ESP32` to line 112 and changing line 113 to `#ifdef` instead of `#if`, compilation and upload complete successfully.

**Comment by gin66** [comment]
Still no idea, what is the problem in the undocumented preprocessor symbol djungle of too many versions.
If you only change `#if` to `#ifdef` without `#define`, does it work ?

If `CONFIG_IDF_TARGET_ESP32` is defined, but evaluates to 0, then this could occur, too.

**Comment by rorosaurus** [comment]
Testing only changing `#if` to `#ifdef` and I still get the same `unsupported derivate` error! :/

**Comment by gin66** [comment]
Please try with latest master. Perhaps now it works ?

**Comment by gin66** [comment]
stale
