### ISSUE TITLE
Compiler warnings for deprecated functions

### ISSUE THREAD

**Issue by alba-ado** [gin66/FastAccelStepper#128]
While using the newest espressif32 platform in the PlatformIO, the library gives a compiler warning. The warning is as follows;

`Processing production (platform: espressif32; board: esp32dev; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (4.1.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 3.20001.0 (2.0.1) 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - toolchain-xtensa-esp32 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 33 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <EEPROM> 2.0.0
|-- <Wire> 2.0.0
|-- <FastAccelStepper> 0.25.3
|-- <Arduino-MultiTasking> 1.0.9
Building in release mode
Compiling .pio/build/production/src/main.cpp.o
Generating partitions .pio/build/production/partitions.bin
Compiling .pio/build/production/lib5a1/EEPROM/EEPROM.cpp.o
Compiling .pio/build/production/libd84/Wire/Wire.cpp.o
Compiling .pio/build/production/lib60a/FastAccelStepper-master/FastAccelStepper.cpp.o
/home/ado/.platformio/packages/framework-arduinoespressif32/libraries/Wire/src/Wire.cpp: In member function 'uint8_t TwoWire::requestFrom(uint16_t, uint8_t, bool)':
/home/ado/.platformio/packages/framework-arduinoespressif32/libraries/Wire/src/Wire.cpp:363:15: warning: variable 'err' set but not used [-Wunused-but-set-variable]
     esp_err_t err = ESP_OK;
               ^~~
Archiving .pio/build/production/lib5a1/libEEPROM.a
Indexing .pio/build/production/lib5a1/libEEPROM.a
Compiling .pio/build/production/lib60a/FastAccelStepper-master/PoorManFloat.cpp.o
Archiving .pio/build/production/libd84/libWire.a
Indexing .pio/build/production/libd84/libWire.a
Compiling .pio/build/production/lib60a/FastAccelStepper-master/RampCalculator.cpp.o
Compiling .pio/build/production/lib60a/FastAccelStepper-master/RampGenerator.cpp.o
Compiling .pio/build/production/lib60a/FastAccelStepper-master/StepperISR_avr.cpp.o
Compiling .pio/build/production/lib60a/FastAccelStepper-master/StepperISR_due.cpp.o
Compiling .pio/build/production/lib60a/FastAccelStepper-master/StepperISR_esp32.cpp.o
Compiling .pio/build/production/lib3a6/MultiTasking-master/MultiTasking.cpp.o
Archiving .pio/build/production/libFrameworkArduinoVariant.a
Indexing .pio/build/production/libFrameworkArduinoVariant.a
lib/FastAccelStepper-master/src/StepperISR_esp32.cpp: In member function 'void StepperQueue::init(uint8_t, uint8_t)':
lib/FastAccelStepper-master/src/StepperISR_esp32.cpp:344:62: warning: 'esp_err_t mcpwm_isr_register(mcpwm_unit_t, void (*)(void*), void*, int, intr_handle_data_t**)' is deprecated: interrupt events are handled by driver, please use callback [-Wdeprecated-declarations]
         NULL, ESP_INTR_FLAG_IRAM | ESP_INTR_FLAG_SHARED, NULL);
                                                              ^
In file included from lib/FastAccelStepper-master/src/common.h:75,
                 from lib/FastAccelStepper-master/src/RampGenerator.h:4,
                 from lib/FastAccelStepper-master/src/FastAccelStepper.h:6,
                 from lib/FastAccelStepper-master/src/StepperISR.h:3,
                 from lib/FastAccelStepper-master/src/StepperISR_esp32.cpp:2:
/home/ado/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/include/driver/mcpwm.h:926:11: note: declared here
 esp_err_t mcpwm_isr_register(mcpwm_unit_t mcpwm_num, void (*fn)(void *), void *arg, int intr_alloc_flags,
           ^~~~~~~~~~~~~~~~~~
lib/FastAccelStepper-master/src/StepperISR_esp32.cpp:344:62: warning: 'esp_err_t mcpwm_isr_register(mcpwm_unit_t, void (*)(void*), void*, int, intr_handle_data_t**)' is deprecated: interrupt events are handled by driver, please use callback [-Wdeprecated-declarations]
         NULL, ESP_INTR_FLAG_IRAM | ESP_INTR_FLAG_SHARED, NULL);
                                                              ^
In file included from lib/FastAccelStepper-master/src/common.h:75,
                 from lib/FastAccelStepper-master/src/RampGenerator.h:4,
                 from lib/FastAccelStepper-master/src/FastAccelStepper.h:6,
                 from lib/FastAccelStepper-master/src/StepperISR.h:3,
                 from lib/FastAccelStepper-master/src/StepperISR_esp32.cpp:2:
/home/ado/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/include/driver/mcpwm.h:926:11: note: declared here
 esp_err_t mcpwm_isr_register(mcpwm_unit_t mcpwm_num, void (*fn)(void *), void *arg, int intr_alloc_flags,
           ^~~~~~~~~~~~~~~~~~
Compiling .pio/build/production/FrameworkArduino/Esp.cpp.o
Compiling .pio/build/production/FrameworkArduino/FirmwareMSC.cpp.o
Compiling .pio/build/production/FrameworkArduino/FunctionalInterrupt.cpp.o
Archiving .pio/build/production/lib60a/libFastAccelStepper-master.a
Indexing .pio/build/production/lib60a/libFastAccelStepper-master.a
Compiling .pio/build/production/FrameworkArduino/HWCDC.cpp.o`

**Comment by gin66** [comment]
Actually similar issue I had reported to (espressif)[https://github.com/espressif/esp-idf/issues/7890] and this deprecation warning should not happen in later releases. At least, they have linked to a commit, which removes the deprecation warning.

**Comment by alba-ado** [comment]
Ok. Thank you.

Closing this issue.
