### ISSUE TITLE
per-stepper auto enable/disable

### ISSUE THREAD

**Issue by barbiani** [gin66/FastAccelStepper#155]
Hello everybody,

I noticed that when running two steppers, the auto enable does not disable the 1st stepper after the run.

The code looks like it supports one enable pin per stepper. Am I right?

In case of multiple steppers with different enable pin and the second stepper is moved to a distant position like 10 million, the first stepper that moved to a close position reaches its destination and never disables the enable pin, while the second stepper steps indefinitely.

**Comment by gin66** [comment]
Yes, one enable pin per stepper is the normal case. Which uC do you use and could you please share the code?
