### ISSUE TITLE
esp32c3

### ISSUE THREAD

**Issue by pyalot** [gin66/FastAccelStepper#156]
Wanted to give this library a spin. Threw an error that esp32c3 isn't supported. Any particular reason or just an oversight?

**Comment by gin66** [comment]
Not an oversight. C3 is not supported: (https://github.com/gin66/FastAccelStepper#esp32c3esp32-mini-1)

The reason is, that I do not have this device, so I cannot test it.

**Comment by evansgl** [comment]
C3 is getting very popular. Any chance to support it, please?

**Comment by gin66** [comment]
Just have ordered two boards. Will arrive around November

**Comment by gin66** [comment]
First version with esp32c3 support has been pushed.

**Comment by evansgl** [comment]
works great! Thanks
