### ISSUE TITLE
Queue is Idle

### ISSUE THREAD

**Issue by markwightman** [gin66/FastAccelStepper#157]
What is the correct way to detect when a motor move command has completed?

I am setting the move command in an interrupt routine which is working okay yet in the Arduino main loop having to implement a delay to get the motor is Idle correctly?
I would of thought the isQueueRunning() would update immediately to being busy?
Regards
Mark

**Comment by gin66** [comment]
it is not guaranteed, that isQueueRunning() is immediately update after the move or similar command. isRunning() is a better choice. Calling the move command from an interrupt routine is not recommended.
