### ISSUE TITLE
TinsyS3

### ISSUE THREAD

**Issue by markwightman** [gin66/FastAccelStepper#158]
Hi,
Will this library support the new TinyS3?

From what I can see it is nearly identical to the TinyPico just more memory, few more pins and WIFI?

Thank you

**Comment by gin66** [comment]
TinyS3 uses ESP32S3, which is not supported at the moment. I would expect, that the required changes are minimal to get it running. Any PR with the required changes is welcome.

**Comment by gin66** [comment]
HeldeReis has provided PR #162. I have merged it. Please try
