### ISSUE TITLE
relative move() after stopMove() continues old move

### ISSUE THREAD

**Issue by microtronics** [gin66/FastAccelStepper#172]
I encountered a bug that becomes present when switching from 0.29.0 to 0.29.1:
When performing a move that is being interrupted by stopMove() (called from an interrupt) and then performing a relative move(1) the driver will continue the stopped move.

```
move(-1000);
interrupt -> stopMove(); //light barrier triggered
delay(10000); //wait time doesn't matter
move(1);  //motor moves in negative direction until reaching -1000 first
```

I currently can't replicate the issue without interrupts

**Comment by microtronics** [comment]
The bug is still present using the master branch. The delay really doesn't matter here. I can even hear the stepper driver switching to hold current, so the motor has really come to a full stop. 

It also seems to be tightly related to Interrupts:
```
volatile int pinState;
void swInterrupt() {
    pinState = digitalRead(SW_PIN);
    if (pinState) {
        stepper->stopMove();
    }
}

void setup() {
    pinMode(SW_PIN, INPUT_PULLUP);
    attachInterrupt(digitalPinToInterrupt(SW_PIN), swInterrupt, CHANGE);
    pinState = digitalRead(SW_PIN);
    sei();
}

void babyStepOut(void) {
    while (pinState)
    {
        stepper->move(1);
        delay(1);
    }
}
```

After the light barrier is hit, the babyStepOut() function is used, to slowly move out of it again. Even when i just comment out the `while (pinState)` statement it works fine. 0.29.0 behaves as expected. Very strange!

**Comment by gin66** [comment]
Good analysis. I have modified the test (examples/Issue172) to issue two `move()` directly after each other and it fails. So I have a test case to working on debugging

**Comment by gin66** [comment]
New fix has passed all pc_based and simavr_based tests. The rework has been more intensive than expected. stopMove() sets again a flag, which will be reset in the stepperTask and the targetPosition adjusted as needed for a stop with deceleration. Any following move() will use that adjusted targetPosition. Looks more reasonable to me.

There is still a race condition: If `move()/moveTo()` is called and then stopMove() is invoked (e.g. from Interrupt) _before_ the stepperTask could process. The `move()/moveTo()` _before_ that `stopMove()`will be processed as if the sequence has been `stopMove()` and then `move()/moveTo()`. As fixing this would be quite difficult, I leave this as it is.

Please try, if the new version works for you.

**Comment by microtronics** [comment]
Sorry, busy times here. It works as expected again. I wonder if the remaining bug you describe is of practical relevance. Currently, I cannot think of a real world example that would stop a move after starting it and before the motor actually turned
