### ISSUE TITLE
0.30.4: - Fix for issue #178: speed does not decelerate but jumps to lower value

### ISSUE THREAD

**Issue by mgroz** [gin66/FastAccelStepper#183]
This still might be a problem using a NEMA17 motor with MicroStepDriver. 

My setup is as follows:
- Hardware: arduino atmega2560, Stepper Driver: https://www.amazon.com/dp/B08PKJG2ND?ref=ppx_pop_mob_ap_share&th=1

Trying To:
- Generating an equivalent pulse/sec (hz) that uses a different number of pickups on a rotating wheel. The sensor is mounted above the wheel and will sense the spoke/nuts. The formula:
(Desired Sensor Output In Hz/(spokes or nuts on wheel))*stepper_driver_switch_setting= stepper_rate/sec setting for FastAccelStepper

The stepper driver is set to 3200 steps per revolution. My setup uses 8 nuts on the wheel and I'm trying to generate 92Hz. Based on the above formula, the STEPPER->setSpeedInHz = 36800. My hardware pins are: 
ENGINE.stepperConnectToPin(6), setDirectionPin(9),setEnablePin(10,false);
The software sets setAutoEnable(true). Movements use runForward();stopMove(); For stopping, I also call isStopping() to wait for motor to halt.

Using setAcceleration(5000), I can run 2hz, 52Hz both up and down. I can spin the motor up to 92Hz. The problem occurs when I try stopping at 92 Hz. The motor starts locking up and skipping. I've tried setting the setAcceleration(2000), still have issues. 

Am I doing something wrong or is the 0.30.4 still an issue ?

I appreciate anything you can do to help me with this issue.

Thanks

**Comment by gin66** [comment]
Could you please make a short sketch, which illustrates the phenomenon and causes the issue in your setup ?

**Comment by gin66** [comment]
Thanks for the description. Based on it, I have set up a test case for 2560 and apparently there is an issue. Will look into the root cause during the weekend

**Comment by gin66** [comment]
OK. after some more analysis, I have identified an unrelated issue: If the stepper is in keep running mode and then `move()` is called, the calculated target position was nonsense. Now it uses the queue end position as reference for the relative `move()`.

Unfortunately, this does not explain your issue.

So I am wondering, if the error is related to interrupt management. Running the stepper at 38500 steps/s means an interrupt every 27us. This would mean, the acceleration is not really related to the issue. Perhaps the pulse counter interrupt/setup/deinit prevents interrupt processing in time, or receiving bytes from the serial interface. Can you eventually not use the pulse counter interrupt or try to find a relation between stepper issue and issueing a serial command ?

**Comment by gin66** [comment]
Thanks for looking into the possibility for long interrupt blockage. If this is not the cause, then I am currently out of ideas. At long as I have no way to reproduce it, I have nothing to work on. So thanks for your support to getting this clarified.

`stopmove()` only sets a flag, which is then evaluated by the cyclic stepper task. This means, it can take up to 4ms until that flag is processed and the ramp state is changing. On the other hand `isStopping()` takes this flag into consideration and returns true, until ramp state switches to IDLE or another call like `move()`, `moveTo()`.... takes place. Was there any problem, why you have changed to `rampState()`.

BTW: Could be an option to offer a blocking variant `void stopMove(bool block=false)` !?

**Comment by gin66** [comment]
Wow. Great finding and root cause analysis. I will add this to the Lessons Learned section to point this out for future app developers.

BTW: For spinning up aka starting a move, there exists already blocking versions.
```
int8_t move(int32_t move, bool blocking = false);
int8_t moveTo(int32_t position, bool blocking = false);
```
Only `runForward()`, `runBackward()` and `stopMove()` have no blocking parameter. Should be easy to add this feature.

**Comment by gin66** [comment]
Just have seen, that a blocking runForward() and runBackward() would never return….
So only stopMove() makes sense
