### ISSUE TITLE
migrating from AccelStepper

### ISSUE THREAD

**Issue by guestisp** [gin66/FastAccelStepper#196]
Hi all.
i'm planning the migration from accelstepper trying to reach higher speed on a ESP32.

I'm not using accelerations or anything else except basic movement commnad, is this a sort of drop-in replacement for accelstepper or should I adjust the code ?

**Comment by gin66** [comment]
Not exactly drop in, as the API has differences. Nevertheless adaptation should be straightforward

**Comment by guestisp** [comment]
uhm non exactly straightforward as i have to recalculate all speeds, as currently i'm using speeds in steps*sec but this library wants a different value.

also, i didnt find anything to check the current position over the movement, in example step 78 over 150

**Comment by gin66** [comment]
stale
