### ISSUE TITLE
"Unsupported board" error for Uno and Pro Mini

### ISSUE THREAD

**Issue by arion-p** [gin66/FastAccelStepper#20]
Using the library on Arduino Uno or Arduino Pro Mini fails with "Unsupported board" error.

**Comment by gin66** [comment]
The check for the two boards nano and atmega2560 have been removed in 0.15.1
Please check, if it works now for you

**Comment by arion-p** [comment]
Now I get:
>.pio\libdeps\Uno\FastAccelStepper\src\StepperISR_avr.cpp:41:25: error: 'stepPinStepper1A' was not declared in this scope

In StepperISR_avr.cpp, line 11 should be:
`#if defined(__AVR_ATmega328P__)`

**Comment by ixil** [comment]
I didn't modify the flags for the other board definitions than the 2560, sorry @gin66 
`__AVR_ATmega328P` should be  `ARDUINO_AVR_ATmega328P` as per https://github.com/platformio/platform-atmelavr/blob/master/boards/ATmega328P.json

It is hard to tell from my phone however if that's everything

**Comment by arion-p** [comment]
`ARDUINO_AVR_ATmega328P` doesn't seem to work.

**Comment by gin66** [comment]
Updated to 0.15.2
Now the code does not check for specific board types, but only for CPU

**Comment by arion-p** [comment]
Working fine here, both Uno and Pro Mini
