### ISSUE TITLE
Stepper does not move small steps with 16bit value input

### ISSUE THREAD

**Issue by particlerain** [gin66/FastAccelStepper#219]
Hi,

thanks for the amazing library.

With accelstepper or other standart stepper libraries i can receiive 16 bit DMX values by using two channels and i can control the stepper with normal and fine steps modes. 
But can't get it done with FastAccelStepper library. 
The stepper moves only to the val1 values. Looks like your library does not accept the 16 bit values  of val2.

eg.
float  val1 = (map(DMXSerial.read(board_dmx_adress + 0),0,255,0,65535)); // Ch1 Normal
float  val2 = DMXSerial.read(board_dmx_adress + 1); // Ch2 Fine (256 steps only)

long target = (val1 + val2);
stepper->moveTo(target);

Any idea how to solve that issue?
Thanks.

**Comment by gin66** [comment]
what are the values or value ranges of val1 and val2 ?

**Comment by gin66** [comment]
If it is about interrupt timing, then it will be difficult: With atmega2560 or atmega328p every step requires one interupt. If you go one stepper at max speed, There will be every 20us an interupt. FastAccelStepper blocks up to ~13us in an interrupt (worst case). If serial driver blocks for >7us, it may get problematic. 

With 250kBaud at 8N1, DMX will give you another 25000 Interrupts/s, so every 40us. So worst case will come out quite reliable.

what is surprising, that the deviation is so big. Can it be, that buffer overruns occur ?

**Comment by gin66** [comment]
if you need high speed, perhaps esp32 is a better choice

**Comment by gin66** [comment]
Happy to hear, that esp32 works much better.

For the quirks: I don’t think, I can help you further. But in case the dmx reader is in one task and another task is using those numbers for controlling FastAccelStepper, then - if I would be in your position - I would check for interprocess communication issues between those two tasks.
