### ISSUE TITLE
Implementatioon on Arduino Giga R1 - running chip - STM32H747XiH6

### ISSUE THREAD

**Issue by programmeddeath1** [gin66/FastAccelStepper#228]
Will the library work as is in the new Arduino Giga R1 -  https://docs.arduino.cc/hardware/giga-r1-wifi/. 

The arduino architecture is as is but the chip running inside is STM32H747XiH6. 

The board is supported on the arduino-ide with a Giga mbed OS. The platformio support was also resolved last week.

Do you think it should logically work with the board? Should I be doing any more analysis, before I purchase it and try on the board?

Thanks for your help in advance!

**Comment by gin66** [comment]
STM32 is not supported in the current version.
