### ISSUE TITLE
Will the library work with AC Servo Motors?

### ISSUE THREAD

**Issue by programmeddeath1** [gin66/FastAccelStepper#230]
I wanted to know if the library will work with AC Servo Motors?

I have this servo motor - https://pdf.indiamart.com/impdf/27505187955/9355230/ac-servo-motor.pdf.

It possibly runs with the same Direction/Pulse logic. Will I be able to run it with the same library?

Thanks for your help in Advance!

**Comment by gin66** [comment]
FastAccelStepper does not drive any stepper directly. It still relies on a stepper driver, which translates step/dir/enable into the phased voltages to control the actual stepper motor. Glancing over the linked site, I could not find any info, that step/dir is supported by the electronics controlling that motor.

**Comment by programmeddeath1** [comment]
[RS Series Servo System Start Guide.pdf](https://github.com/gin66/FastAccelStepper/files/14123851/RS.Series.Servo.System.Start.Guide.pdf)

Hi  you can check this file.

For your reference page number 5 shows the Pul/Step control terminals for the driver.

**Comment by gin66** [comment]
the spec is not really clear for step interface. Is it now 24V ? must it be be a differential signal? is the step on positive or negative edge.

**Comment by programmeddeath1** [comment]
![image](https://github.com/gin66/FastAccelStepper/assets/44861370/c0ff2fe0-f918-4793-9e5f-3c7c4df8a641)

It shows control through differential 5V supply. I can just confirm if its step on rising or falling edge, but the rest seems like it could work with the same setup right?

**Comment by petmakris** [comment]
The Differential input 5V most probably means the inputs are opto-coupled so a floating 5V pulse between PUL+ and PUL+ will activate the input.

You can try and generate some pulses with an arduino or a square wage signal generator into them pins.
If this will work, the library will work too. 

Your question is not really relevant to this project though

**Comment by gin66** [comment]
In case you can connect the PUL- to GND and PUL+ to output of the uC, then it should be ok for an avr. For an esp32, which does not output 5V, still a level shifter is needed.

**Comment by programmeddeath1** [comment]
Hi yes thank you for your input guys, it should ideally work, but just wanted to confirm. I am running even the esp32 on Hybrid Drivers with 5V triggers, because usually for some 5V systems the HIGH trigger is at 2.8V and thus the esp32 with 3.3V is also able to provide the pulse triggers properly, else ofcourse I have level shifters for relay's etc which require higher min voltage more than 3.3V.
