### ISSUE TITLE
Execution frequency

### ISSUE THREAD

**Issue by programmeddeath1** [gin66/FastAccelStepper#241]
I am trying to run my motors for a robot through this library, I am sending the trajectory to the esp with control cycle of 0.04, which means it sends around 25 points every second. with a control cycle of 0.01, it sends 100 msgs a second or 1 traj msg every 10ms. Will the library be able to generate and execute these different velocity/acceleration/position values every 10ms and send it to the driver?

**Comment by gin66** [comment]
If you send a trajectory with 10ms resolution, then the ramp generation from FastAccelStepper is not relevant. For that use case, it is better to employ the [low level interface](https://github.com/gin66/FastAccelStepper/blob/master/extras/doc/FastAccelStepper_API.md#low-level-stepper-queue-management-low-level-access).

**Comment by gin66** [comment]
Answering your question: The stepper task is run every 4ms and will fill the command queue up to 20ms into the future (pre-planning). Existing commands in the queue will not be changed anymore e.g. by new values for position/speed/acceleration.

**Comment by programmeddeath1** [comment]
@gin66 when you say the ramp generation from FastAccelStepper is not relevant, does it mean it will not have an effect on the 10ms executions? Is the PWM signal generation time insignificant for FastAccelStepper?

**Comment by gin66** [comment]
I mean, if the trajectory is fully controlled by the application, then the ramp generator has nothing to do.

For better reaction time, #253 is added to adjust forward planning time

**Comment by gin66** [comment]
Implementation released in 0.30.13
