### ISSUE TITLE
Release 0.30.15 not in master code branch

### ISSUE THREAD

**Issue by sharpie7** [gin66/FastAccelStepper#267]
I opened the repo on a different computer and still wasn't seeing v0.30.15 in master. Opening [the commit ](https://github.com/gin66/FastAccelStepper/commit/490e2939cf31e8b24465df76a10bc265280acbe6)shows that the commit isn't in a branch:
![image](https://github.com/gin66/FastAccelStepper/assets/9697874/917f9437-9b35-43c9-91fe-f4b9a795ae7c)

Seems to be a Git problem somewhere!

**Comment by gin66** [comment]
No idea, how this has come. Now I have rewritten the master branch and looks good to me.
Thanks for the hint.
