### ISSUE TITLE
How many steppers can you control with acceleration?

### ISSUE THREAD

**Issue by digitalbird01** [gin66/FastAccelStepper#39]
I have been working on a motion control system using accelstepper for many months. The obvious drawback is that I can only control one stepper while implementing acceleration control. Can your library control two or more steppers with at least common acceleration values ? If so which board would you recommend. I am currently working with the RF-Nano

**Comment by gin66** [comment]
All connected steppers are independently controlled by acceleration and speed parameters and all steppers can run in parallel.

The RF-Nano is based on atmega328p, correct ? Then there are 2 steppers supported and there are two acceleration and speed parameters. One pair per stepper.

With the Atmega2560 you can drive three steppers in parallel.

Performance wise, I would recommend esp32 (AFAIK not the s2), which can run up to 6 steppers in parallel
