### ISSUE TITLE
Controlling the pulse width

### ISSUE THREAD

**Issue by XenuIsWatching** [gin66/FastAccelStepper#42]
Is there a way to set the pulse width. It looks like it's currently about 5us on the nano.

**Comment by gin66** [comment]
No. The pulse is set to high by the output compare match and set to low in the interrupt.

Changing it configurable, would me

**Comment by lboclboc** [comment]
It seems my driver card does not react on a 5us pulse. How would I solve this? Is there not way to make a fixed patch for creating a longer pulse. I can't find in the code where the timer is set to 5 us.
