### ISSUE TITLE
Typo, bad paste & copy or forgotten ?

### ISSUE THREAD

**Issue by macedolfm** [gin66/FastAccelStepper#45]
FastAccelStepper.c, line 484

_enablePinHighActive && _enablePinHighActive ?

```
  if ((_enablePinHighActive == PIN_UNDEFINED) &&
      (_enablePinHighActive == PIN_UNDEFINED)) {
    _externalEnableCall = NULL;
  }
```

**Comment by gin66** [comment]
Thanks for the report. Some typos are hard to find and there is no test for it either.
Anyway, I have fixed the code in master. It will be included in the next release.
