### ISSUE TITLE
attachInterrupt on avr

### ISSUE THREAD

**Issue by etempm** [gin66/FastAccelStepper#61]
I am using rotary optical encoder to check and compensate lost steps on arduino uno. Encoder code uses hardware  "attachInterrupt" and with fastaccellstepper motor hangs / no movement. If I comment the code line "attachInterrupt" it works as expected. Anything I need to know?

By the way very good library and thanks for your effort.

**Comment by gin66** [comment]
The attachInterrupt() connects to which pin and what is in the ISR?

**Comment by etempm** [comment]
Hardware interrupt as I said. Pins 2 and 3 on uno. And no ISR code.

**Comment by gin66** [comment]
What are the parameters to attachInterrupt() ? The second parameter is the ISR function.
```
attachInterrupt(digitalPinToInterrupt(pin), ISR, mode) (recommended)
attachInterrupt(interrupt, ISR, mode) (not recommended)
attachInterrupt(pin, ISR, mode) (Not recommended. Additionally, this syntax only works on Arduino SAMD Boards, Uno WiFi Rev2, Due, and 101.)
```

**Comment by etempm** [comment]
Like this,

#define encoder0PinA 2
#define encoder0PinB 3
------

pinMode(encoder0PinA, INPUT_PULLUP);
 pinMode(encoder0PinB, INPUT_PULLUP);
 
attachInterrupt(0, doEncoderA, CHANGE);
attachInterrupt(1, doEncoderB, CHANGE);

**Comment by gin66** [comment]
Looks ok. How do the doEncoderA() and doEncoderB() functions look like ?

**Comment by gin66** [comment]
btw: please check for [Rotary encoder issue](https://github.com/gin66/FastAccelStepper/issues/44)

**Comment by etempm** [comment]
Read methods just some fast port read code asm.

void doEncoderA(){
  // look for a low-to-high on channel A
  if (ReadPinA() == HIGH) {
    // check channel B to see which way encoder is turning
    if (ReadPinB() == LOW) { 
      encoder0Pos = encoder0Pos + 1;         // CW
    }
    else {
      encoder0Pos = encoder0Pos - 1;         // CCW
    }
  }
  else   // must be a high-to-low edge on channel A                                       
  {
    // check channel B to see which way encoder is turning 
    if (ReadPinB() == HIGH) {   
      encoder0Pos = encoder0Pos + 1;          // CW
    }
    else {
      encoder0Pos = encoder0Pos - 1;          // CCW
    }
  }
  Serial.println (encoder0Pos, DEC);         
  // use for debugging - remember to comment out
}

byte ReadPinA()//PIN2
{
  //return digitalRead(2);
  byte rtx=LOW;
  asm (
  "in __tmp_reg__, __SREG__  \n"
  "cli                       \n"                     
  "ldi %0, 1                 \n" //high 
  "sbis %1, %2               \n" //skip next if pin high
  "clr %0                    \n" //low
  "out __SREG__, __tmp_reg__ \n"
  : "=r" (rtx) : "I" (_SFR_IO_ADDR(PIND)), "I" (PIND2)  
);

      return rtx;
}

byte ReadPinB()//PIN3
{
   //return digitalRead(3);
  byte rtx=LOW;
  asm (
  "in __tmp_reg__, __SREG__  \n"
  "cli                       \n"                     
  "ldi %0, 1                 \n" //high 
  "sbis %1, %2               \n" //skip next if pin high
  "clr %0                    \n" //low
  "out __SREG__, __tmp_reg__ \n"
  : "=r" (rtx) : "I" (_SFR_IO_ADDR(PIND)), "I" (PIND3)  
);

      return rtx;
}

void doEncoderB(){
  // look for a low-to-high on channel B
  if (digitalRead(encoder0PinB) == HIGH) {   
   // check channel A to see which way encoder is turning
    if (digitalRead(encoder0PinA) == HIGH) { 
      encoder0Pos = encoder0Pos + 1;         // CW
    }
    else {
      encoder0Pos = encoder0Pos - 1;         // CCW
    }
  }
  // Look for a high-to-low on channel B
  else {
    // check channel B to see which way encoder is turning 
    if (digitalRead(encoder0PinA) == LOW) {   
      encoder0Pos = encoder0Pos + 1;          // CW
    }
    else {
      encoder0Pos = encoder0Pos - 1;          // CCW
    }
  }
}

**Comment by devrim-oguz** [comment]
Your Interrupt Service Routine (ISR) uses cli which disables the interrupts for the microprocessor. Which what the stepper library needs in order to work. It can't generate interrupts while your ISR is running.

**Comment by etempm** [comment]
Yes... In asm, I fogot that. Thanks. I will test it. (Devrim bey teşekkür ederim.)

**Comment by gin66** [comment]
any update ?

**Comment by etempm** [comment]
Hi,
 I disabled ISR code. But same, no change. This is all code.

#include "FastAccelStepper.h"
#include "AVRStepperPins.h" // Only required for AVR controllers
//
#define encoder0PinA 2
#define encoder0PinB 3
volatile int encoder0Pos = 0;

#define dirPinStepper    5
//#define enablePinStepper 6
#define stepPinStepper   9

// If using an AVR device use the definitons provided in AVRStepperPins
//    stepPinStepper1A
//
// or even shorter (for 2560 the correct pin on the chosen timer is selected):
//    stepPinStepperA

FastAccelStepperEngine engine = FastAccelStepperEngine();
FastAccelStepper *stepper = NULL;
int yol=5066;
void setup() {

   engine.init();
   stepper = engine.stepperConnectToPin(stepPinStepper);
   if (stepper) {
      stepper->setDirectionPin(dirPinStepper);
      //stepper->setEnablePin(enablePinStepper);
      //stepper->setAutoEnable(true);

      stepper->setSpeedInHz(16000);       
      stepper->setAcceleration(8000);  
      stepper->moveTo(yol);
   }
}

void loop()
{

if (stepper->getCurrentPosition()==yol)
{
   stepper->moveTo(0);
}
else if (stepper->getCurrentPosition()==0)
{
   stepper->moveTo(yol);
}
}

-------------------------------

void doEncoderA(){
  // look for a low-to-high on channel A
  if (ReadPinA() == HIGH) {
    // check channel B to see which way encoder is turning
    if (ReadPinB() == LOW) { 
      encoder0Pos = encoder0Pos + 1;         // CW
    }
    else {
      encoder0Pos = encoder0Pos - 1;         // CCW
    }
  }
  else   // must be a high-to-low edge on channel A                                       
  {
    // check channel B to see which way encoder is turning 
    if (ReadPinB() == HIGH) {   
      encoder0Pos = encoder0Pos + 1;          // CW
    }
    else {
      encoder0Pos = encoder0Pos - 1;          // CCW
    }
  }
  Serial.println (encoder0Pos, DEC);         
  // use for debugging - remember to comment out
}

byte ReadPinA()//PIN2
{
  return digitalRead(2);
}

byte ReadPinB()//PIN3
{
   return digitalRead(3);
}

void doEncoderB(){
  // look for a low-to-high on channel B
  if (digitalRead(encoder0PinB) == HIGH) {   
   // check channel A to see which way encoder is turning
    if (digitalRead(encoder0PinA) == HIGH) { 
      encoder0Pos = encoder0Pos + 1;         // CW
    }
    else {
      encoder0Pos = encoder0Pos - 1;         // CCW
    }
  }
  // Look for a high-to-low on channel B
  else {
    // check channel B to see which way encoder is turning 
    if (digitalRead(encoder0PinA) == LOW) {   
      encoder0Pos = encoder0Pos + 1;          // CW
    }
    else {
      encoder0Pos = encoder0Pos - 1;          // CCW
    }
  }
}

**Comment by gin66** [comment]
In the latest code, the encoder is not in use at all. Initially the stepper has been operated, if interrupt has not been attached to the pin. So please first check your setup, if the steppers are still operable. Or go back to the old code, which has worked.

**Comment by gin66** [comment]
stale issue
