### ISSUE TITLE
[question] Is it possible to invert direction pin?

### ISSUE THREAD

**Issue by oaklandGman** [gin66/FastAccelStepper#62]
Is there a way to invert the direction pin output, so my motor will run the opposite direction in regards to positive / negative values? For example, positive values make the motor turn clockwise, but I would like it to turn anti-clockwise. 

I'll run the output of the micro through a logic inverter if I need to, just checking to see if it's possible in software first.

Thanks!

**Comment by gin66** [comment]
Yes, the second parameter allows it `void setDirectionPin(uint8_t dirPin, bool dirHighCountsUp = true);`. Just set to false

**Comment by oaklandGman** [comment]
Oh duh I should have noticed that in the include file - thanks for the fast response!
