### ISSUE TITLE
Accelerate and decelerate while spinning

### ISSUE THREAD

**Issue by H3adsho0ot** [gin66/FastAccelStepper#64]
Hey,

first of all incredible Lib! Do you think it would be possible to add a feature to modify the speed while endlessly spinning the stepper (increase and decrease)?

Thanks in advance

**Comment by gin66** [comment]
If I understand you correctly, then it is implemented like this. Just need to modify the speed by one of the setSpeed calls and call `applySpeedAcceleration()`.

If this does not work as expected, please clarify for my better understanding, what you need

**Comment by H3adsho0ot** [comment]
I missed the applySpeedAcceleration .... sorry for that - works flawlessly!
