### ISSUE TITLE
Using in continuous rotation mode

### ISSUE THREAD

**Issue by yankobogdan** [gin66/FastAccelStepper#65]
I need to run stoppers continuously for a long time. 
For now, the best option to do its setting position in steps to max value then continuously monitor the position to reset it when it's would be close to desired. But it's not efficient to spent resource to call pos check function often
In the description, I see that continuous operation (rotation) in a particular direction is possible
"Allows the motor to continuously run in the current direction until stopMove() is called"
Can you advise which function should I call to achieve continuous rotation in one direction until stopMove() would be called?

Many thanks

**Comment by gin66** [comment]
guess you have found it: runForward() and runBackward() do the trick
