### ISSUE TITLE
How to stopMove without disabling steppers?

### ISSUE THREAD

**Issue by MahOraibi** [gin66/FastAccelStepper#72]
I really love this library as it does everything I need except for this small thing. I'm using it to move 2 steppers with a joystick however I couldn't find any function to stop moving without putting the motors in idle state or freewheeling state. This is really important because one of the motors is used for tilting and whenever I use stopMove() function the z axis falls down. Is there a way to stop movement without disabling the steppers?

**Comment by gin66** [comment]
Apparently you are using `setAutoEnable(true)`. So you have two options:
1. `setAutoEnable(false)`: in this case, the stepper needs to be manually enabled
2. `setDelayToDisable(uint16_t delay_ms)` with a large number for delay_ms

**Comment by gin66** [comment]
stale issue
