### ISSUE TITLE
How is Positioning Using a GearHead Handled Within FastAccelStepper

### ISSUE THREAD

**Issue by vepicurean** [gin66/FastAccelStepper#77]
Hi: 

I know this is question item. But these no place to put questions. I'm hoping someone has run into this before with FastAccelStepper with using a gearhead with a step motor and has some suggestions on how to handle it. 

We've been working with FastAccelStepper and reading the PulseCounter to count the pulses from our ESP32 MCU to the step motore from -25599 to 0 through to 25599  (using register 7) microsteps. It has been working well in the way we were using the step motor previously to and mapping the microsteps to degrees. 

The issue we've run into is when we added a 100:1 planetary gearhead for more power to manage the load on the step motor. And now our 1:1 microsteps to degrees positioning approach to convert microsteps to degrees from 0 to 359 degrees does not work for us.  The  gearhead shaft position does not have a 1:1 relationship anymore with the microsteps (steps) read from the pulse counter. 

Adjusting the code using FastAccelStepper for the faster speed of the motor shaft and relating this to the gearhead shaft using the ticks was easy. The speed measurement and control we just had to make a few adjustments by a factor of 100. 

But the positioning adjustments to reflect the gearhead shaft does not move in line with the pulse counter. We've been at for a few days now,  and nothing we try to map the gearhead shaft position to the pulse counter on the main motor shaft turns out to be accurate. 

Ideally, we'd have just read the pulse counter and divide by a factor of 100 to reflect the fact the 100:1 gearhead shaft only moves 1/100 as far as the motor shaft. Because the pulse counter resets every 25600 steps to the zero value, that logic can only apply for the first (just 1) revolution of the motor shaft (which is nothing as far as the displacement/movement of the gearhead shaft is concerned).   

Does anyone have any suggestions on how to deal with this 100:1 gearhead positioning challenge using FastAccelStepper?

Note: One thing we did look at is trying to apply the concept that the gearhead shaft's motion (small movements relative to the main shaft) could be represented using a register and the pulse counter given the fact that the 100:1 gearhead shaft has higher effective resolution of 25600 steps x 100 gear ratio = 2,560,000 effective steps. So from -2,559,999 to 0 then to 2,559,999 effective steps to represent the gear head shaft.  So something like effective steps = 1/100 x the step value, 2/100 x step value..... through to 100/100 x step value from reading the pulse counter. Then converting that to degrees from 0 to 359 degrees. But this does not/will not work because of the resetting to 0 on the main motor shaft counter p7 -25599 to 0 through to 25599.

**Comment by gin66** [comment]
Thanks for the question und use of FastAccelStepper. Nice to hear, that you can use it. 

Reading through your post, I wonder, if switching to the position reported from the driver could be a solution. This is a 32bit signed integer value and would fulfill your purpose. Either `getPositionAfterCommandsCompleted()` or `getCurrentPosition()`

Besides   for the gearbox - if you change direction - do you have an estimate, how many steps to perform until the 100:1 shaft starts rotating in opposite direction? Or is there a constant load, so that the gearbox slack is not occurring?

**Comment by vepicurean** [comment]
Thanks. Greatly appreciate the input. 

We were able to use the `getCurrentPosition` function in our logic to create the virtual microstep positioning for the gearhead shaft.  Then combined with the speed of the gearhead, we were about to re-edit our previous logic. We just need to work with the timings more to get things as accurate as possible. 

Because we're just moving in once direction, the backlash from the gearhead is not too bad. We do notice that we need to do our times using a range of microsteps depending on the resolution of the gearhead. This 100:1 gearhead gives a virtual resolution of 25600 microsteps x 100 = 2,560,000 virtual microsteps in 360 degrees. It hard to say execute a specific event at virtual microstep position 1,920,000.  We have to use some logic to execute the target event at say 1,919,975 to 1,920,030.   

I hope this makes sense. 

Thanks for all the help. We're moving now and just a matter of some experiments to get the timing under the gearhead driven virtual positioning as exact as possible.

**Comment by gin66** [comment]
As the ramp generation is relatively well predictable, the time to run to the position 1,919,975….1,920,030 can be calculated. Only wondering, if it is worth the effort for implementation, because polling the position at 1ms ready is not too costly on an esp32 and less complex

Anyway, happy to hear, that you have found a working solution
