### ISSUE TITLE
Where is the description of the commands of FastAcccelSteper?

### ISSUE THREAD

**Issue by quangbinhhvac** [gin66/FastAccelStepper#89]
Hi gin66,
I couldn't find the library's command descriptions

**Comment by gin66** [comment]
As per Readme:

For the API definition please consult the header file [FastAccelStepper.h](https://github.com/gin66/FastAccelStepper/blob/master/src/FastAccelStepper.h).

Hope this is sufficient

**Comment by quangbinhhvac** [comment]
Thank you so very much

**Comment by quangbinhhvac** [comment]
really great library, I just found out about it
