### ISSUE TITLE
 I have problems with speed and distance traveled

### ISSUE THREAD

**Issue by quangbinhhvac** [gin66/FastAccelStepper#90]
Hi gin66,

my distance is set to constant 2 laps. but when i change the speed it is wrong
and it also no longer holds true when i change the delay time so i have to add the function "delay(100);" I do not understand why

void runZ() {
  int microstep = 800;
  long x = a*microstep; //xung/s
  long y = a*10*microstep; //xung/s^2 tăng tốc trong 100 miliseconds
  long z = (b/10)*microstep; // số xung hành trình
  if (stepperZ) {
     stepperZ->setDirectionPin(dirPin1);
     stepperZ->setEnablePin(enablePin1);
     stepperZ->setAutoEnable(true);
     
     stepperZ->setSpeedInHz(x);       // steps/s
     stepperZ->setAcceleration(y);    // steps/s²
     stepperZ->moveTo(-z);
     delay(100);
     kichZ();
     delay((c/10) * 1000); //trễ (c/10)*1000 miliseconds
     digitalWrite(kich, LOW);
     stepperZ->moveTo(0);
  }
}

**Comment by gin66** [comment]
the `move()` only starts the process, while the application in `loop()` is continue to run. So `move()` or `moveTo()` are NOT blocking. If there is the need to wait for the stepper running, then check for `isRunning()`

**Comment by quangbinhhvac** [comment]
it mean:
1. problem 1:
microstep 800, step 1.8
I put moveTo(1600) 
run speed 900 RPM, it's so good
but run speed 40 RPM, it doesn't go to the location
2. problem 2:
if there is no function delay(100), it doesn't go to the location

**Comment by gin66** [comment]
yes. Without delay(), the code executes moveTo(1600) and then immediately moveTo(0). So the stepper runs towards 0, where it already is. So will not run to 0.
You have to wait after moveTo(1600), that the stepper reaches that position. And only then issue moveTo(0)

**Comment by gin66** [comment]
I see, there is no simple usage example, which shows simple running forward and backward.

**Comment by quangbinhhvac** [comment]
moveTo(1600) and moveTo(0) it is overwritten.  it doesn't run in order

**Comment by gin66** [comment]
That's what I mean: moveTo() is NOT blocking.

**Comment by gin66** [comment]
Try this (hope it compiles):
```
void loop() {
     if (!stepper->isRunning()) {
         uint32_t pos = stepper->getCurrentPosition();
         stepper->moveTo(1600-pos);
     }
}
```

**Comment by quangbinhhvac** [comment]
#include <Wire.h> //khai báo thư viện
#include <EEPROM.h> //khai báo thư viện
#include "FastAccelStepper.h"
#include "AVRStepperPins.h" // Only required for AVR controllers
FastAccelStepperEngine engine = FastAccelStepperEngine();
FastAccelStepper *stepperZ = NULL;
#include <LiquidCrystal_I2C.h>     //Thư viện LiquidCrystal_I2C: https://github.com/ArduinoKIT/Luc-Nguyen/raw/master/LiquidCrystal_I2C-1.1.2.zip
LiquidCrystal_I2C lcd(0x27, 16, 2); //kích thước LCD
#define up A0
#define down A1
#define runn A2
#define CTHT A3
#define outputA 11
#define outputB 12
#define sw 13
#define stepPin1 9
#define dirPin1 8
#define enablePin1 A6
#define kich 10
int counter = 0;
int aState;
int aLastState;
double a = EEPROM.read(0); //Speed đọc giá trị tại ô nhớ 0 
double b = EEPROM.read(1); //H.Tr đọc giá trị tại ô nhớ 1
double c = EEPROM.read(2); //Tre đọc giá trị tại ô nhớ 2
//...............................................
void setup() {
  Serial.begin(9600);
  pinMode(up , INPUT_PULLUP);
  pinMode(down , INPUT_PULLUP);
  pinMode(runn , INPUT_PULLUP);
  pinMode(CTHT , INPUT_PULLUP);
  pinMode(outputA , INPUT);
  pinMode(outputB , INPUT);
  pinMode(sw , INPUT_PULLUP);
  pinMode(stepPin1, OUTPUT);
  pinMode(dirPin1, OUTPUT);
  pinMode(enablePin1, OUTPUT);
  pinMode(kich, OUTPUT);
  aLastState = digitalRead(outputA); //gán giá trị xung outputA cuối là aLastState
  lcd.init();
  lcd.backlight();
  lcd.setCursor(0, 0);
  lcd.print("Speed");
  lcd.setCursor(7, 0);
  lcd.print("H.Tr");
  lcd.setCursor(13, 0);
  lcd.print("Tre");
  engine.init();
  stepperZ = engine.stepperConnectToPin(stepPin1);
}
//...............................................
void loop() {
ok:
  lcd.setCursor(1, 1);
  lcd.print(a); //in ra LCD giá trị tốc độ
  lcd.setCursor(3, 1);
  lcd.print("   ");
  lcd.setCursor(7, 1);
  lcd.print(b/10); //in ra LCD giá trị hành trình
  lcd.setCursor(10, 1);
  lcd.print("  ");
  lcd.setCursor(13, 1);
  lcd.print(c/10); //in ra LCD giá trị trễ
  if ((a < 0) || (b < 0) || (c < 0))
  {
    lcd.setCursor(0, 0);
    lcd.print("                ");
    lcd.setCursor(0, 1);
    lcd.print("                ");
    lcd.setCursor(5, 1);
    lcd.print("ERROR!");
  }
  while (digitalRead(sw) == 0)
  {
    unsigned long time1 = millis();
    while (1) {
      if ((millis() - time1) > 3000) {
        a = 0;
        b = 0;
        c = 0;
        lcd.setCursor(5, 1);
        lcd.print("      ");
        goto ok;
      }
      if (digitalRead(sw) == 1)
      {
        readVR();
        goto ok;
      }
    }
  }
  if (digitalRead(up) == 0) {
    digitalWrite(dirPin1, LOW);
    trucZ();
  }
  if (digitalRead(down) == 0) {
    digitalWrite(dirPin1, HIGH);
    trucZ();
  }
  if ((digitalRead(runn) == 0)&&(stepperZ->isRunning() == false)) { //nếu ấn nút và step không chạy
    runZ();
  }
  if (digitalRead(CTHT) == 0) {
    kichTAYHAN();
  }
}
//...............................................
void readVR() {
  while (1) {
    lcd.setCursor(0, 1);
    lcd.print(">");
    counter = a;
    delay(500);
    while (1) {
      aState = digitalRead(outputA); //đọc giá trị xung chân outputA gán là aState
      if (aState != aLastState) //nếu giá trị aState thay đổi khác giá trị cuối aLastState tiến hành so sánh mức giá trị xung outputB
      {
        if (digitalRead(outputB) != aState) { //nếu giá trị xung tại outputA khác outputB tức là quay thuận ta tăng biến đếm
          counter++; //tăng biến đếm, quay thuận
        }
        else {
          counter--; //nếu sai thì giảm biến đếm, quay nghịch
        }
        //Serial.println(counter);
        if (counter > 30 ) { //giới hạn tốc độ tối đa 30 v/s ~ 30 biến đếm (max 1800v/phút)
          counter = 30;
        }
        if (counter < 1 ) { //giới hạn tốc độ tối thiểu 1 v/s ~ 1 biến đếm (min 60v/phút)
          counter = 1;
        }
        a = counter;
        lcd.setCursor(1, 1);
        lcd.print(a);
        lcd.setCursor(3, 1);
        lcd.print("   ");
      }
      aLastState = aState; //nhớ lại giá trị hiện xung tại aState vào biến aLastState để tiếp tục so sánh
      if (digitalRead(sw) == 0) {
        goto b;
      }
    }
  }
b:
  while (1) {
    lcd.setCursor(0, 1);
    lcd.print(" ");
    lcd.setCursor(6, 1);
    lcd.print(">");
    counter = b;
    delay(500);
    while (1) {
      aState = digitalRead(outputA);
      if (aState != aLastState)
      {
        if (digitalRead(outputB) != aState) {
          counter++;
        }
        else {
          counter--;
        }
        //Serial.println(counter);
        if (counter > 99 ) { //hành trình tối đa đặt tối đa là 9.9v ~ 99 biến đếm ~ 49.5mm với vitme bước 5 (thông số này tùy thuộc vào vitme ví dụ vime bước 5mm là 1v đi được 5mm)
          counter = 99;
        }
        if (counter < 1 ) { //hành trình tối thiểu đặt tối thiểu là 0.1v ~ 1 biến đếm ~ 5mm với vitme bước 5
          counter = 1;
        }
        b = counter;
        lcd.setCursor(7, 1);
        lcd.print(b/10);
        lcd.setCursor(10, 1);
        lcd.print("  ");
      }
      aLastState = aState;
      if (digitalRead(sw) == 0) {
        goto c;
      }
    }
  }
c:
  while (1) {
    lcd.setCursor(6, 1);
    lcd.print(" ");
    lcd.setCursor(12, 1);
    lcd.print(">");
    counter = c;
    delay(500);
    while (1)
    {
      aState = digitalRead(outputA);
      if (aState != aLastState)
      {
        if (digitalRead(outputB) != aState) {
          counter++;
        }
        else {
          counter--;
        }
        //Serial.println(counter);
        if (counter > 50 ) { //trễ cuối hành trình đặt tối đa là 5s ~ 50 biến đếm
          counter = 50;
        }
        if (counter < 0 ) { //trễ cuối hành trình đặt tối thiểu là 0s ~ 0 biến đếm
          counter = 0;
        }
        c = counter;
        lcd.setCursor(13, 1);
        lcd.print(c/10);
      }
      aLastState = aState;
      if (digitalRead(sw) == 0) {
        goto d;
      }
    }
  }
d:;
  EEPROM.write(0, a); //lưu giá trị vào ô nhớ 0
  EEPROM.write(1, b); //lưu giá trị vào ô nhớ 1
  EEPROM.write(2, c); //lưu giá trị vào ô nhớ 2
  lcd.setCursor(12, 1);
  lcd.print(" ");
  delay(500);
}
//...............................................
void trucZ() {
  while ((digitalRead(up) == 0) || (digitalRead(down) == 0)) {
    digitalWrite(stepPin1, HIGH);
    delayMicroseconds(500);
    digitalWrite(stepPin1, LOW);
    delayMicroseconds(500);
  }
}
//...............................................
void runZ() {
  int microstep = 800;
  long x = a*microstep; //xung/s
  long y = a*10*microstep; //xung/s^2 tăng tốc trong 100 miliseconds
  long z = (b/10)*microstep; // số xung hành trình
  if (stepperZ) {
     stepperZ->setDirectionPin(dirPin1);
     stepperZ->setEnablePin(enablePin1);
     stepperZ->setAutoEnable(true);
     
     stepperZ->setSpeedInHz(x);       // steps/s
     stepperZ->setAcceleration(y);    // steps/s²
     stepperZ->moveTo(-z);
     delay(100);
     kichZ();
     delay((c/10) * 1000); //trễ (c/10)*1000 miliseconds
     digitalWrite(kich, LOW);
     stepperZ->moveTo(0);
  }
}
void kichZ() {
    digitalWrite(kich, HIGH);
}
void kichTAYHAN() {
    digitalWrite(kich, HIGH);
    delay(500);
    digitalWrite(kich, LOW);
}

**Comment by quangbinhhvac** [comment]
help me make it move better

**Comment by gin66** [comment]
Move this to` setup()`:
```
stepperZ->setDirectionPin(dirPin1);
stepperZ->setEnablePin(enablePin1);
stepperZ->setAutoEnable(true);
```

Besides, I have no idea, what your code shall do, but you can try this:
```
 delay(100);
 kichZ();
 while(stepperZ->isRunning()) { /* wait */ }
 digitalWrite(kich, LOW);
 stepperZ->moveTo(0);
```

**Comment by quangbinhhvac** [comment]
thank you so much. I made it run as I wanted. Your library is amazing. Thank you for taking the time to help me

**Comment by quangbinhhvac** [comment]
Hi gin66,
Have a good day
I have another problem that is:
when i call the function "stepperZ->setEnablePin(enablePin1, true);" i see the motor shaft is not held, so is enablePin1 high. and when I set it to low "digitalWrite(enablePin1, LOW);" then "moveTo" doesn't work

**Comment by gin66** [comment]
Please check for `stepperZ->setAutoEnable(true);`
If set to false, enable is always on.
Alternatively, call `setDelayToDisable(uint16_t delay_ms);` with a suitable long delay for your needs.

**Comment by quangbinhhvac** [comment]
i mean when i set stepperZ->setAutoEnable(true) the axis can be rotated manually i.e Enable is in HIGH it should be LOW

**Comment by gin66** [comment]
not clear. If you have called `moveTo()` before, then the motor is running.Right ?

So I assume, the problem of „not held“ is after the move is completed, or before the very first move.

With `autoEnable()`, the driver will enable the motor with configured polarity - just before the move starts. After the move, the driver will disable the motor again. Any application’s `digitalWrite(enablePin1, LOW)` will be overwritten. As there is no call to `setDelayToDisable(uint16_t delay_ms);`, the driver will nearly immediately turn off the driver after a move is completed and the motor will not be held.

So apparently the auto enable feature may not work for you, so you could use this  sequence instead:
```
stepperZ->setAutoEnable(false);
stepperZ->enableOutputs();
```

**Comment by quangbinhhvac** [comment]
i called  "stepperZ->setEnablePin(enablePin1, true);
                stepperZ->setDirectionPin(dirPin1, true);
                stepperZ->setAutoEnable(true);" at void setup. 
then the motor has not rotated, moveTo has not been called, I tried turning the motor shaft manually, but the motor doesn't hold

**Comment by gin66** [comment]
If auto enable is set to true, then the driver will not touch the enable pin at all before any move()/....

**Comment by quangbinhhvac** [comment]
when i call so enablePin1 will be high or low?

**Comment by gin66** [comment]
If you call setEnablePin(), the following code is executed (some error detection code removed for better clarity):
```
void FastAccelStepper::setEnablePin(uint8_t enablePin,
                                    bool low_active_enables_stepper) {
  if (low_active_enables_stepper) {
    if (enablePin != PIN_UNDEFINED) {
      digitalWrite(enablePin, HIGH);
      pinMode(enablePin, OUTPUT);
    }
  } else {
    if (enablePin != PIN_UNDEFINED) {
      digitalWrite(enablePin, LOW);
      pinMode(enablePin, OUTPUT);
    }
  }
}
```

So after this call, the enable pin is set to OFF.
=> If the motor is fixed, then the polarity given is low_active_enables_stepper wrong. If the motor is free, all is ok.
=> If the motor is free, then it works as expected.

**Comment by quangbinhhvac** [comment]
I don't understand it very well maybe because of my ability, I will try to find out more what you say

**Comment by quangbinhhvac** [comment]
So when I call the function "stepperZ->setAutoEnable(true)" what will happen.
stepperZ->setEnablePin(enablePin1, true) and stepperZ->setAutoEnable(true) are superfluous

**Comment by gin66** [comment]
The purpose of `setEnablePin()` and `setAutoEnable()` are not superfluous at all. 

`setEnablePin()` tells the library **HOW** to enable/disable the stepper motor output drivers.

`setAutoEnable()` tells the library **WHEN** to enable/disable the stepper motor output drivers. If false, then the stepper library does not enable/disable the output drivers automatically and the application programmer has to enable/disable explicitly with `enableOutputs()`/`disableOutputs()`. If true, then the stepper library will enable the output drivers automatically before a move and disable them after a move. The exact timing is defined by the enable/disable delays.

**Comment by quangbinhhvac** [comment]
as far as i understand setAutoEnable will set Enalble to HIGH right before the first move and LOW at the start of the move, right after stopping it goes back to HIGH
I think so right?

**Comment by gin66** [comment]
If low_active_enables_stepper=true  as parameter to setEnablePin() has been set, then  yes. The „right after“ can be changed by these calls:
```
  // In auto enable mode, the stepper is enabled before stepping and disabled
  // afterwards. The delay from stepper enabled till first step and from
  // last step to stepper disabled can be separately adjusted.
  // The delay from enable to first step is done in ticks and as such is limited
  // to MAX_ON_DELAY_TICKS, which translates approximately to 120ms for
  // esp32 and 60ms for avr at 16 MHz). The delay till disable is done in period
  // interrupt/task with 4 or 10 ms repetition rate and as such is with several
  // ms jitter.
  void setAutoEnable(bool auto_enable);
  int8_t setDelayToEnable(uint32_t delay_us);
  void setDelayToDisable(uint16_t delay_ms);
```

**Comment by quangbinhhvac** [comment]
I want it to always be LOW is the engine operating level, what functions should I call?  i don't want it to turn off/on/off like with the autoenable function doing because it's out of sync with some function i call from stepper default library

**Comment by gin66** [comment]
as I have written above:
```
stepperZ->setAutoEnable(false);
stepperZ->enableOutputs();
```

**Comment by quangbinhhvac** [comment]
can you help me a command with push button at A0,A1 and step will rotate reversibly if button is pressed, release push button step will stop

**Comment by quangbinhhvac** [comment]
Thank you very much. You helped me a lot, thanks

**Comment by quangbinhhvac** [comment]
the commands are in the file FastAccelStepper.h, where can I find a detailed explanation of it

**Comment by quangbinhhvac** [comment]
I find it not very detailed.  Is there any more detail?

**Comment by quangbinhhvac** [comment]
Thank you very much.
